ready
sapalks/web-course-back pull request #13
Opened 2021-02-21 10:02 UTC by PowerWarrior12

2021-02-22 04:48 UTC, sapalks requested changes
Код от первой лабы. Отчет от второй. Что то не то. И где видео с демонстрацией первой лабы?

2021-02-22 05:06 UTC, sapalks commented
Очень странное схожесть вашего readme с [этим](https://github.com/sapalks/web-course-back/pull/12/files#diff-0ad0484efc62245d4bcf1515776b8d9a0a572b0d49e88bb5a20298003b0e832c).

2021-02-22 05:11 UTC, sapalks commented
А реализация похожа на [эту](https://github.com/sapalks/web-course-back/blob/master/PI21_Tyapukhin_Vlad_lab_01/index.js) и [эту](https://github.com/sapalks/web-course-back/blob/master/PIbd22_Romanov_Aleksey_lab_01/index.js)

2021-02-22 05:20 UTC, sapalks commented
Раз так неудачно спалились, вот вам еще задание:
необходимо реализовать 2 запроса:
1. GET запрос для перевода из имперских мер для жидкостей в привычные нам литры. В качестве параметров передается числовое значение и единица измерения, вы возвращаете кол-во литров, эквивалентное переданному объему.
2. POST запрос для извлечения всех чисел из строки. В теле запроса передается предложение с числами. Ваша задача - найти в строке все числа и вернуть их массив обратно. К примеру если пришел в запросе данный комментарий до этих слов, то вы должны вернуть:
```json
{
  "body" : [ 2, 1, 2 ]
}
```

2021-02-28 12:35 UTC, PowerWarrior12 commented
Сделал

2021-03-07 08:16 UTC, sapalks commented
Принято

2021-03-07 08:16 UTC, merged