Pi22 mazyakov vladislav lab 11
sapalks/web-course-back pull request #167
Opened 2021-05-22 05:58 UTC by Quenby-apr

2021-05-26 07:55 UTC, sapalks requested changes

2021-05-26 07:55 UTC, sapalks commented on PI22_Mazyakov_Vladislav_lab_11/controller/board.js
> +            cache.save('board', boards.rows)
а в чем смысл подобного кеша? когда вы в запись с ключем 'board' можете записать и объект и массив
к примеру я сначала запросу данные по записи с id=1, вы закешите все, а потом я запрошу данные у записи с id=3, но вы мне вернете инфу из записи с id=1 из за такого кеша.
В ключе должна содержаться информация о запросе, идентификатор сущности или ключей фильтров, если вы работаете с множеством записей

2021-05-28 19:54 UTC, Quenby-apr commented on PI22_Mazyakov_Vladislav_lab_11/controller/board.js
> +            cache.save('board', boards.rows)
Замечание исправлено, теперь он после ключевого слова добавляет id необходимой записи, если выборка идёт по Id, то есть появляется ключ advert14, если мы искали запись advert с id = 14

2021-05-29 07:20 UTC, sapalks approved these changes

2021-05-29 07:21 UTC, merged