Pibd21_Yuhlimov_Peter_lab_02_ready
sapalks/web-course-back pull request #20
Opened 2021-03-06 13:19 UTC by PowerWarrior12

2021-03-07 08:48 UTC, sapalks requested changes

2021-03-07 08:48 UTC, sapalks commented on PIbd21_Yuhlimov_Peter_lab_02/server/controller/book.controller.js
> +        const book = await db.query('SELECT * FROM book WHERE bookId = $1',[id])
не забывайте проверять записи, удалены они или нет., аналогично и  в других GET запросах

2021-03-13 07:47 UTC, PowerWarrior12 commented
Сделал

2021-03-21 06:29 UTC, merged

2021-03-21 06:29 UTC, sapalks commented
Принято