Pi22 filippov nikita lab 03 is ready
sapalks/web-course-back pull request #32
Opened 2021-03-17 14:01 UTC by Nike073i

2021-03-17 14:02 UTC, Nike073i commented
https://drive.google.com/file/d/1RMk-6V9nc1tO7_2Kg5Y92aC_NI4jRse2/view?usp=sharing

2021-03-21 06:13 UTC, sapalks requested changes
Здорово! 

С большинством нуюансов вы разобрались самостоятельно, круто! Не есть несколько моментов, которые не лежат на поверхности, но которые стоит учитывать.

Сейчас у вас сценарии сильно зависят друг от друга, нельзя взять и прогнать только один из тестов (на получение и редактирование данных к примеру), потому что этих данных не будет.

Для того, что бы не возникало такой ситуации, тесты должны быть максимально автономными и перед выполнением теста необходимо очищать содержимое бд. Пример, как очищать бд для посгри я скидывал в задании. Теперь давайте разберемся, как вызывать эту команду для каждого теста. Для этого используются "хуки" (hooks).
Подробнее тут: https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/hooks.md
Что с этим делать? Берем хук `Before` и в нем вызываем apicall для очистки бд.
```
Before(function () {
  this.api().clear()
});
```

После этого для теста метода GET или UPDATE вам надо опять создать запись (важно, что тут вы уже не тестируете создание, вы тестируете чтение/редактирование)
Для этого используется команда GIVEN. Фактически она работает как и WHEN, только после не ожидает проверку THEN.

```js
Given("a client added hotel with name {string}, with rating {string} in country with id {string}, with address {string} and with contact number {string}",
function (Name,Rating,CountrieID,Address,ContactNumber){
    this.api().addHotel(Name,Rating,CountrieID,Address,ContactNumber);
    this.assetOk() // это командой мы чистим в объекте world запрос и ответ, так как нас они не интересуют, важно только то, что бы он отработал
});


// в файле root.js

assetOk() {
   expect(this.response.statusCode).to.eql(200);
   this.forget();
}

```

Далее. По поводу наличия id в описании тестов. Это плохо. Обычно они автоинкрементируемые или guid (если честно, я не понял, как вы добились того, что вам всегда возвращается один и тот же id), поэтому заранее знать, что вам придет не получится. Таким образом при проверке ответов обычно все поля, которые динамически меняются (id, create date, update date) удаляются или не сравниваются.
Реализация данного подхода присутствует в файле https://github.com/sapalks/web-course-back/blob/master/_examples/e2e-test/features/steps/common.js
Там есть 2 THEN. 
`server must reply with the following json in body:` - он удаляет поле id и сравнивает модели на эквивалентность
`server must reply with a json in body like:` - он сравнивает, что бы в ответе присутствовали все перечисленные поля, т.е. с сервера может вернуться больше, но ошибку это не породит.

Теперь, когда мы не знаем заранее id, возникает вопрос, как узнать в тесте id и отправить по нему запрос?

В файле мира при создании записи используем такую конструкцию:
```js
    #id;
    getLastId() {
        return this.#id;
    }
    create() {
        this.post('/create', body);
        this.#id = this.response.body.id
    }
```
И далее из steps мы сможем получать последний id, созданный в рамках данного мира.

2021-03-21 06:13 UTC, sapalks commented on PI22_Filippov_Nikita_lab_03/features/support/world/api.js
> +class ApiWorld extends BaseWorld {
в рамках мира `World` в данной концепции подразумевается мир определенной сущности, в вашем случае это будет 2 мира, мир стран и мир отелей. Это используется для повышения читабельности кода.
```js
//in steps
this.api().deleteHotel(Id);
//vs
this.hotel().delete(Id);

```

2021-04-11 17:25 UTC, Nike073i commented
Замечания исправлены. Прикрепляю скриншот
![Результат тестов](https://user-images.githubusercontent.com/63452427/114314551-4b4a3780-9b0c-11eb-96d8-e10f562a62e0.png)

2021-04-25 05:25 UTC, sapalks approved these changes
Принято

2021-04-25 05:25 UTC, merged