Pibd 21 yuhlimov peter lab 04
sapalks/web-course-back pull request #35
Opened 2021-03-30 15:16 UTC by PowerWarrior12

2021-04-04 08:27 UTC, sapalks requested changes

2021-04-04 08:27 UTC, sapalks commented on PIbd21_Yuhlimov_Peter_lab_04/server/controller/user.controller.js
> +        else{
небольшой хак, как сделать код читабельнее.
откажитесь от `else` используйте эту конструкцию только в совершенно тупиковых ситуациях. тут можно было это оформить следующим образом

```js
if(condition){
    do smth
    return;
}
logic in else
```

2021-04-04 08:27 UTC, sapalks commented on PIbd21_Yuhlimov_Peter_lab_04/server/controller/user.controller.js
> +            if (safepassword.rows[0] == null){
на видео вы зарегистрировали пользователя с паролем 12345678, а для авторизации использовали пароль 1234567. Не так должна работать авторизация)) И дело в этом условии. Во первых по базе надо проверять связку логин+пароль. В вашей же можно указать логин одного пользователя, а пароль другого и система это съест.

2021-04-17 10:32 UTC, PowerWarrior12 commented
Исправил

2021-04-25 05:09 UTC, sapalks approved these changes

2021-04-25 05:09 UTC, sapalks commented
ПРинято

2021-04-25 05:09 UTC, merged