PI22_Mayorov_Yury_lab_01 is ready
sapalks/web-course-back pull request #5
Opened 2021-02-12 05:51 UTC by mayst1230

https://yadi.sk/i/-4CkkeOQlV1iyA

2021-02-14 09:03 UTC, sapalks requested changes

2021-02-14 09:03 UTC, sapalks commented on PI22_Mayorov_Yury_lab_01/index.js
> +	res.status(500).send('Error')
500 ошибка - это не обработанная ошибка, считается дурным тоном и косяком разработчика. обработанные ошибки должны быть в пределе 4** кода, однако коды есть не под все ситуации, поэтому есть подход, когда обработанные ошибки возвращаются с 200 кодом, но в теле запроса описан статус и тест ошибки. 

Давайте так и переделаем. Во все успешные запросы вы добавляете `"status" : "ok"`, как в примере с пингом.
А во всех ошибках тело ответа выглядит следующим образом:
```js
{
  "status": "error",
  "message": "текст ошибки(деление на 0 и т.д."
}
```

2021-02-18 11:45 UTC, mayst1230 commented on PI22_Mayorov_Yury_lab_01/index.js
> +	res.status(500).send('Error')
@sapalks Внес изменения

2021-02-22 05:02 UTC, sapalks approved these changes

2021-02-22 05:02 UTC, merged