lab02 is ready
sapalks/web-course-back pull request #6
Opened 2021-02-12 19:03 UTC by silvathebest

Видео - https://youtu.be/NQ3cyBZwlm8

curl http://localhost:8080/user
curl http://localhost:8080/user/?id={id}
curl -X POST http://localhost:8080/user
curl -X PUT http://localhost:8080/user
curl -X DELETE http://localhost:8080/user?id={id}

curl http://localhost:8080/project
curl http://localhost:8080/project?customerId={customerId}
curl http://localhost:8080/project/?id={id}
curl -X POST http://localhost:8080/project
curl -X PUT http://localhost:8080/project
curl -X DELETE http://localhost:8080/project/?id={id}

2021-02-14 08:53 UTC, sapalks requested changes

2021-02-14 08:53 UTC, sapalks commented on PIbd22_Romanov_Aleksey_lab_02/controller/project.js
> +        await db.query('DELETE FROM customer_project where projectid = $1', [id])
Удаление данных из бд - плохая и очень ресурс затратная операция, поэтому в задании я писал, что бы вы `помчали запись удаленной`
Почему плохая:
- Во первых это не обратимая или сложно обратимая операция. Допустим ваш продукт в продакшене, есть пользователи, и один из них случайно удаляет нужные данные (его сотрудник по незнанию это делает, или наоборот специально удаляет, что бы перед (или из за) увольнением подпортить все). Если вы реально удалили  данные из базы, то для восстановления придется отдельно разворачивать последний бекап базы данных и переносить из нее эти данные.
- Это очень ресурсоемкая операция, так как она не только очищает данные, но и вызывает переиндексацию. 
- Операция удаления (если данные, которые удаляются имеют динамический размер) приводит к сильной дефрагментации базы данных.

По этому обычно в таблицах, где подразумевается удаление записей добавляется флаг, отвечающий, удалена ли запись, или нет. К примеру `isDeleted (bit)`

Если данных много и они быстро устаревают, то обычно операцию удаления делают раз в интервал времени (к примеру раз в сутки ночью, когда клиентская активность минимальна), после чего идет одна операция переиндексации. Для более сложных задач используется технология шардирования баз данных. Но об этом позже.

Так что переделайте пожалуйста удаление на редактирование (просто помечаем isDeleted) и соответственно остальные запросы на работу с этим флагом

2021-02-16 20:55 UTC, silvathebest commented
Исправил удаление, теперь данные помечаются как удаленные через колонку isDeleted
Поменял создание базы данных в файле database.sql

2021-02-22 05:00 UTC, sapalks approved these changes

2021-02-22 05:01 UTC, merged